package com.supportmind.analytics;

import io.swagger.v3.oas.annotations.media.Schema;

import java.time.LocalDate;
import java.util.List;
import java.util.Map;

public final class AnalyticsDtos {

    private AnalyticsDtos() {
    }

    public record AnalyticsResponse(DateRange range, Overview overview, List<DailyMessages> messagesPerDay,
                                    Map<String, Long> ticketsByPriority, Map<String, Long> ticketsByCategory) {
    }

    /** Rango de fechas en UTC: {@code from} incluido, {@code to} incluido. */
    public record DateRange(LocalDate from, LocalDate to) {
    }

    public record Overview(
            @Schema(description = "Conversations created in the range") long totalConversations,
            @Schema(description = "Tickets currently open (OPEN, IN_PROGRESS or WAITING)") long openTickets,
            @Schema(description = "Tickets resolved in the range") long resolvedTickets,
            @Schema(description = "Average time from the first customer message to the first reply (AI or agent)")
            Double averageResponseTimeSeconds,
            @Schema(description = "Conversations answered by the AI in the range") long aiHandledConversations,
            @Schema(description = "Share of AI-handled conversations answered without any human handoff")
            Double aiResolutionRate,
            @Schema(description = "Share of AI-handled conversations the AI handed off to a human")
            Double humanHandoffRate,
            @Schema(description = "Average confidence of the answers generated by the AI") Double averageAiConfidence,
            long totalMessages) {
    }

    public record DailyMessages(LocalDate date, long total, long customer, long ai, long agent) {
    }
}
