package com.supportmind.audit;

public enum AuditEvent {
    ORGANIZATION_CREATED,
    ORGANIZATION_SETTINGS_UPDATED,
    USER_REGISTERED,
    USER_CREATED,
    USER_LOGIN,
    CUSTOMER_CREATED,
    CONVERSATION_CREATED,
    CONVERSATION_ASSIGNED,
    CONVERSATION_STATUS_CHANGED,
    MESSAGE_SENT,
    AI_RESPONSE_GENERATED,
    AI_HANDOFF,
    AI_SUGGESTION_ACCEPTED,
    AI_SUGGESTION_REJECTED,
    TICKET_CREATED,
    TICKET_UPDATED,
    KNOWLEDGE_DOCUMENT_CREATED,
    KNOWLEDGE_DOCUMENT_UPDATED
}
